# build: docker build -t generalmeow/rethinkdb:<TAG>-arm
# run: docker run -d -p 28015:28015 -p <>:8080 --name rethinkdb -v <>:/var/lib/rethinkdb/default -v <>:/var/log/rethinkdb generalmeow/rethinkdb:<TAG>-arm
FROM resin/rpi-raspbian
MAINTAINER Paul Hoang 2017-01-16
EXPOSE 28015
EXPOSE 8080
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "libprotobuf9", "-qy"]
RUN ["mkdir", "-p", "/home/rethinkdb/files"]
RUN ["mkdir", "-p", "/home/rethinkdb/data"]
RUN ["mkdir", "-p", "/home/rethinkdb/logs"]
RUN ["touch", "/home/rethinkdb/logs/log"]
RUN ["chown", "-R", "root:root", "/home/rethinkdb"]
COPY ["./files", "/home/rethinkdb/files"]
RUN ["/home/rethinkdb/files/rethinkdb-arm-2.3.5/catFiles.sh"]
RUN ["mv", "/home/rethinkdb/build/rethinkdb-2.3.5", "/home/rethinkdb"]
RUN ["rm", "-rf", "/home/rethinkdb/files"]
COPY ["./files/etc/rethinkdb/instances.d/instance.conf", "/etc/rethinkdb/instances.d/instance.conf"]
VOLUME /var/lib/rethinkdb/default
VOLUME /var/log/rethinkdb
WORKDIR /home/rethinkdb/build/rethinkdb-2.3.5
ENTRYPOINT ["./rethinkdb", "--config-file", "/etc/rethinkdb/instances.d/instance.conf"]
