# build: docker build -t generalmeow/rethinkdb:<TAG>-arm
# run: docker run -d -p 28015:28015 -p <>:8080 --name rethinkdb -v <>:/var/lib/rethinkdb/default -v <>:/var/log/rethinkdb generalmeow/rethinkdb:<TAG>-arm
FROM resin/rpi-raspbian
MAINTAINER Paul Hoang 2017-01-16
EXPOSE 28015
EXPOSE 8080
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "libprotobuf9", "-qy"]
RUN ["apt-get", "clean", "libprotobuf9", "-qy"]
RUN ["mkdir", "-p", "/home/rethinkdb/data"]
RUN ["mkdir", "-p", "/home/rethinkdb/logs"]
RUN ["touch", "/home/rethinkdb/logs/log"]
COPY ["./build/rethinkdb-2.3.5", "/home/rethinkdb"]
COPY ["./files/etc/rethinkdb/instances.d/instance.conf", "/etc/rethinkdb/instances.d/instance.conf"]
VOLUME /var/lib/rethinkdb/default
VOLUME /var/log/rethinkdb
WORKDIR /home/rethinkdb
ENTRYPOINT ["./rethinkdb", "--config-file", "/etc/rethinkdb/instances.d/instance.conf"]
